### ISSUE TITLE
Bolt Extension OpenGraph Generates Incorrect Image URL

### ISSUE THREAD

**Issue by Malaysiatic** [GawainLynch/bolt-extension-opengraph#1]
The extension is not generating the correct URL for the image it is using, it generates the full page URL followed by /files/example-image.jpg

As an example the og image URL is showing:

meta property="og:image" content="http://www.example.com/page/my-latest-blog-post/files/example-image.jpg" 

Whereas it should be showing:

meta property="og:image" content="http://www.example.com/files/example-image.jpg"

**Comment by GawainLynch** [comment]
Fixed in v2.1.1
